### ISSUE TITLE
Recompile the coffeescript after the pull requests

### ISSUE THREAD

**Issue by timwis** [socrata/soda-js#10]
Looks like @chrismetcalf merged my 3 pull requests but the coffeescript hasn't been compiled into javascript. I intentionally left out the .js files of my PRs because they aren't really 'source' and different compilers seem to produce irrelevant diffs. Happy to compile and submit a PR for the .js file if you like, just let me know.

**Comment by chrismetcalf** [comment]
Good point, and thank you. We should probably look into a build process that'd do that automatically
