### ISSUE TITLE
Access via window in browser

### ISSUE THREAD

**Issue by timwis** [socrata/soda-js#15]
Hey @chrismetcalf, I just tried to use this lib _without_ browserify or require.js and couldn't figure out how. Is there a way to access `soda.Consumer` from the window? I get a `require not defined` error when loading the lib. Perhaps wrapping the lib in UMD would help?

Here's the use case, btw: really easy socrata charts w/amcharts:
http://codepen.io/timwis/pen/mejXgv - especially if they add a way to use the `dataLoader` param in their [builder](http://live.amcharts.com/new/edit/)

**Comment by rantler** [comment]
Looks like `soda-js` uses `require` itself in two places. We'd have to refactor it to fallback to another approach if `require` isn't available.

**Comment by timwis** [comment]
Alternatively, since the file in `/dist` is the built version, you could run `browserify file.js -o output.js` to bundle it, which would pull in its dependencies to be self-contained. You'd still need to fix the `export()` function at the bottom though; I believe that's what's preventing it being called via `window.`

**Comment by timwis** [comment]
btw, I requested AmCharts add `dataLoader` to their live builder and they did :D Now you can build charts using their [builder](http://live.amcharts.com) against a Socrata API. [example](http://live.amcharts.com/JkYTM/) (click 'edit' at top right to see config)

**Comment by marks** [comment]
Very nice @timwis - unless you have time to do it yourself, I am going to do a writeup on live.amcharts.com and show yours as an example. Anything you can share about your use of amcharts in Philly would be great to share with civic developers and state/local governments alike on dev.socrata.com.

Mark

**Comment by timwis** [comment]
Thanks @marks, sounds good!
