### ISSUE TITLE
IE11 gets mad

### ISSUE THREAD

**Issue by marks** [socrata/soda-js#20]
![skitch 1](https://cloud.githubusercontent.com/assets/34566/14589741/81f90324-04b7-11e6-91d0-6531943037e0.png)

**Comment by marks** [comment]
I... think I fixed this with https://github.com/socrata/soda-js/compare/master...marks:20-fix-ie#diff-3

**Comment by chrismetcalf** [comment]
@marks Looks good to my eyeballs, can we get this into a PR and maybe see if we can bribe @clint-tseng into giving it a 👍 too.

**Comment by clint-tseng** [comment]
My only hesitation and confusion is that Underscore.js still uses the `.toString` style check. It also delegates to `Array.isArray` if it's available, but falls back to the toString check, and does so for all other types. But I don't have a _problem_ with the diff, just a confusion.
