### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by hchungen15** [socrata/soda-js#24]
Using the soda-js.bundle.js to load data and getting the errors: 
Cross-Origin Request Blocked
TypeError: response is undefined

**Comment by chrismetcalf** [comment]
Cross-origin requests that aren't `GET`s or contain authentication headers are blocked for security reasons. Allowing them could provide a vector for cross-site scripting attacks that hijack a logged-in user's credentials.

https://dev.socrata.com/docs/cors-and-jsonp.html

You could, however, use soda-js in an authenticated context on the server side, where XSS isn't a risk.

**Comment by hchungen15** [comment]
I'm using Coldfusion script and soda-js to refresh the data. So, how do I authenticate using Coldfusion script. Do I call the following sample HTTP Session through Coldfusion script? Thanks.
---------------------------------------------
POST /resource/4tka-6guv.json HTTP/1.1
Host: soda.demo.socrata.com
Accept: */*
Authorization: Basic [REDACTED]
Content-Length: 253
Content-Type: application/json
X-App-Token: [REDACTED]

**Comment by chrismetcalf** [comment]
@hchungen15 It looks like you've also submitted a trouble ticket via our support team. Since the real solution to your problem is probably going to be in ColdFusion instead of JS, I'm going to close this issue and respond via your trouble ticket instead.
