### ISSUE TITLE
is there any example code using soda-js with upsert?

### ISSUE THREAD

**Issue by kevinsmgov** [socrata/soda-js#26]
I have been trying to test a node.js project to upsert records but I can't get it to give me any event responses - 'success', 'complete', 'progress', 'error' or an onAny function never get emitted.

**Comment by chrismetcalf** [comment]
@kevinsmgov Are you listening on both the `success` and `error` responses? And getting neither?

`upsert` works similar to `add`, and there's an example in the README: https://github.com/socrata/soda-js#producer-api

**Comment by kevinsmgov** [comment]
Yes, I had listener functions on both and neither got called back (also added listeners on 'complete' and 'progress' just in case - they didn't get called back either).

However, I did assume that the upsert method was for multiple records (as it's defined in the REST API). Can it only be called for one record at a time?

**Comment by clint-tseng** [comment]
Can you paste the (maybe simplified) snippet where you make the request and register the listener?

**Comment by chrismetcalf** [comment]
Also, another consideration: How big is the record set you're trying to upsert? Upsert calls are synchronous, so if you were sending a really large set, I'd wonder if a timeout was a factor.

**Comment by kevinsmgov** [comment]
That's a good point. I'll try setting up some different sized payloads.

**Comment by kevinsmgov** [comment]
It was a misunderstanding of node style programming style. Once I got things wired up right, the upsert call worked as expected (even with the large payload)

**Comment by chrismetcalf** [comment]
Awesome, thanks for the update @kevinsmgov
