### ISSUE TITLE
Error on basic query

### ISSUE THREAD

**Issue by timwis** [socrata/soda-js#3]
Getting an error on [soda-js.coffee#L125](https://github.com/socrata/soda-js/blob/master/src/soda-js.coffee#L125): `Uncaught TypeError: Cannot read property 'ok' of null`

Using browserify

```javascript
var soda = require('soda-js');

var consumer = new soda.Consumer('data.cityofchicago.org');

consumer.query()
  .withDataset('xzkq-xp2w')
  .getRows()
    .on('success', function(rows) {
      //console.log('Success', rows);
    })
    .on('error', function(error) {
      console.error('Error', error);
    });
```

Is this lib just out of date? I notice it's not in the libs page

**Comment by clint-tseng** [comment]
Bah, Superagent must have changed their API, and it looks like the package.json didn't lock in a version.

I'll hunt for a working version later today, though if you force the version back about a year it should work. If that works, let me know what worked for you!

**Comment by timwis** [comment]
Thanks for the quick response @clint-tseng - got it working per your advice and submitted a pull request

**Comment by clint-tseng** [comment]
Awesome. Thanks! Merging, and then fixing whatever's up with the tests.
