### ISSUE TITLE
Throttling question

### ISSUE THREAD

**Issue by kylerummens** [socrata/soda-js#39]
Your [Getting Help](https://dev.socrata.com/support.html) page on dev.socrata.com says that questions should be made on stackoverflow and that issues should be submitted here, so I apologize for posting a question here. However, I have posted two questions on stackoverflow and gotten no responses.

I am trying to query different [USAC E-rate databases](https://opendata.usac.org/browse?category=E-rate&limitTo=datasets) using soda-js, but I feel like I am getting throttled. The [Socrata App Token documentation](Socrata App Token documentation) says:

> Without an application, we can only track usage and perform throttling based on a few simple criteria, mainly source IP address. As such, requests that aren’t using an application token come from a shared pool via IP address. IP addresses that make too many requests during a given period may be subject to throttling.

The problem is, though, that I am passing in an app token with all my requests, but some of the SoQL requests that are fairly simple are taking up to 36 seconds to respond. I know some of the datasets have upwards of 70,000 rows, but am I wrong in assuming that a simple query shouldn't take 36 seconds? Does this mean I'm being throttled?

The Socrata Request ID returned with the request was `17b5a244e611eb41caf87bc3ac073dc7`

**Comment by chitang** [comment]
The request was not throttled.  A throttled request will only be rejected instead of taking longer to run.  This is a group by query on 8M rows.

**Comment by kylerummens** [comment]
Ok. So, not being an expert in SQL, is there a way to make the http request quicker than 36 seconds when doing grouping? That seems like an unusual amount of time for a query, but then again I'm not familiar with SQL run times.
